server:
  port: 8081

spring:
  application:
    name: pulse-app
  profiles:
    active: dev

  # 数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pulse?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root123456

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true   # 下划线转驼峰(create_time → createTime)
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   # 打印 SQL 到控制台
  global-config:
    db-config:
      logic-delete-field: isDeleted      # 全局逻辑删除字段
      logic-delete-value: 1               # 删除时设置为 1
      logic-not-delete-value: 0           # 未删除是 0
      id-type: AUTO                       # 主键自增
  mapper-locations: classpath*:mapper/**/*.xml   # mapper xml 位置

logging:
  level:
    com.duanruixin.pulse: DEBUG