server:
  port: 8081

spring:
  application:
    name: pulse-app
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public

logging:
  level:
    com.duanruixin.pulse: DEBUG